Questions:-
1. Consider the dataset containing the gender,salary,age based on which you need to predict whether to purchase a product or not
2. Load the dataset and display all the informations
3. find out the total no of sample and shape
4. Extract the dataset into dependent and independent variables
5. perform the required preprocessing techniques
6. split the dataset into training and testing data
7. Build the logistic regression model using inbuilt library and display the accuracy of the model alongwith the confusion matrix
8. And build the model from scratch as well


Importing libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


load the dataset 

In [2]:
dataframe=pd.read_csv('Dataset_logistic_regression.csv')

In [4]:
dataframe

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

getting shapes 

In [5]:
dataframe.shape

(400, 5)

In [6]:
dataframe.sum()

User ID                                                   6276615903
Gender             MaleMaleFemaleFemaleMaleMaleFemaleFemaleMaleFe...
Age                                                            15062
EstimatedSalary                                             27897000
Purchased                                                        143
dtype: object

In [7]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoding=OneHotEncoder()
sal=one_hot_encoding.fit_transform(dataframe.iloc[:,[1]]).toarray()

In [8]:
print(sal)
print(type(sal))

[[0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 

In [9]:
dataframe.drop(['Gender'],axis=1)

User ID  Age  EstimatedSalary  Purchased
0    15624510   19            19000          0
1    15810944   35            20000          0
2    15668575   26            43000          0
3    15603246   27            57000          0
4    15804002   19            76000          0
..        ...  ...              ...        ...
395  15691863   46            41000          1
396  15706071   51            23000          1
397  15654296   50            20000          1
398  15755018   36            33000          0
399  15594041   49            36000          1

[400 rows x 4 columns]

In [10]:
dataframe.corr()

User ID       Age  EstimatedSalary  Purchased
User ID          1.000000 -0.000721         0.071097   0.007120
Age             -0.000721  1.000000         0.155238   0.622454
EstimatedSalary  0.071097  0.155238         1.000000   0.362083
Purchased        0.007120  0.622454         0.362083   1.000000

In [11]:
dataframe['Gender']=sal

In [12]:
dataframe

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510     0.0   19            19000          0
1    15810944     0.0   35            20000          0
2    15668575     1.0   26            43000          0
3    15603246     1.0   27            57000          0
4    15804002     0.0   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863     1.0   46            41000          1
396  15706071     0.0   51            23000          1
397  15654296     1.0   50            20000          1
398  15755018     0.0   36            33000          0
399  15594041     1.0   49            36000          1

[400 rows x 5 columns]

In [13]:
sal

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.

In [ ]:
from 

In [30]:
Dataset1=dataframe.iloc[:,2:]
Dataset1

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [31]:
x1=Dataset1.iloc[:,:-1]
x1

Age  EstimatedSalary
0     19            19000
1     35            20000
2     26            43000
3     27            57000
4     19            76000
..   ...              ...
395   46            41000
396   51            23000
397   50            20000
398   36            33000
399   49            36000

[400 rows x 2 columns]

In [32]:
y1=Dataset1.iloc[:,-1]
y1

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [33]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
fitting=scalar.fit_transform(x1)
print(fitting)


[[-1.78179743 -1.49004624]
 [-0.25358736 -1.46068138]
 [-1.11320552 -0.78528968]
 [-1.01769239 -0.37418169]
 [-1.78179743  0.18375059]
 [-1.01769239 -0.34481683]
 [-1.01769239  0.41866944]
 [-0.54012675  2.35674998]
 [-1.20871865 -1.07893824]
 [-0.25358736 -0.13926283]
 [-1.11320552  0.30121002]
 [-1.11320552 -0.52100597]
 [-1.6862843   0.47739916]
 [-0.54012675 -1.51941109]
 [-1.87731056  0.35993973]
 [-0.82666613  0.30121002]
 [ 0.89257019 -1.3138571 ]
 [ 0.70154394 -1.28449224]
 [ 0.79705706 -1.22576253]
 [ 0.98808332 -1.19639767]
 [ 0.70154394 -1.40195167]
 [ 0.89257019 -0.60910054]
 [ 0.98808332 -0.84401939]
 [ 0.70154394 -1.40195167]
 [ 0.79705706 -1.37258681]
 [ 0.89257019 -1.46068138]
 [ 1.08359645 -1.22576253]
 [ 0.89257019 -1.16703281]
 [-0.82666613 -0.78528968]
 [-0.63563988 -1.51941109]
 [-0.63563988  0.12502088]
 [-1.01769239  1.97500684]
 [-1.59077117 -1.5781408 ]
 [-0.92217926 -0.75592482]
 [-1.01769239  0.59485858]
 [-0.25358736 -1.25512738]
 [-0.44461362 -1.22576253]
 

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x1,y1,test_size=0.3,random_state=0)


In [35]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)
model.score(x_train,y_train)

0.6357142857142857

In [36]:
predict=model.predict(x_test)
print(len(predict))
predict
print(len(x_test))
print(y_test.iloc[:,])
arr=np.array(y_test)
arr
# print(type(y_test))
arr.sum()


120
120
132    0
309    0
341    0
196    0
246    0
      ..
216    0
259    1
49     0
238    0
343    1
Name: Purchased, Length: 120, dtype: int64


41

In [37]:
from sklearn.metrics import  mean_absolute_error,mean_squared_error,confusion_matrix
print("mae",mean_absolute_error(y_test,predict))
print(confusion_matrix(y_test,predict))

mae 0.3416666666666667
[[79  0]
 [41  0]]


In [38]:
Dataset2=dataframe.iloc[:,1:]
Dataset2

Gender  Age  EstimatedSalary  Purchased
0       0.0   19            19000          0
1       0.0   35            20000          0
2       1.0   26            43000          0
3       1.0   27            57000          0
4       0.0   19            76000          0
..      ...  ...              ...        ...
395     1.0   46            41000          1
396     0.0   51            23000          1
397     1.0   50            20000          1
398     0.0   36            33000          0
399     1.0   49            36000          1

[400 rows x 4 columns]

In [39]:
x=Dataset2.iloc[:,:3]

In [40]:
x

Gender  Age  EstimatedSalary
0       0.0   19            19000
1       0.0   35            20000
2       1.0   26            43000
3       1.0   27            57000
4       0.0   19            76000
..      ...  ...              ...
395     1.0   46            41000
396     0.0   51            23000
397     1.0   50            20000
398     0.0   36            33000
399     1.0   49            36000

[400 rows x 3 columns]

In [41]:
y=Dataset2.iloc[:,-1]
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [42]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
fitting1=scalar.fit_transform(x)
print(fitting1)
print(len(fitting1))

[[-1.02020406 -1.78179743 -1.49004624]
 [-1.02020406 -0.25358736 -1.46068138]
 [ 0.98019606 -1.11320552 -0.78528968]
 ...
 [ 0.98019606  1.17910958 -1.46068138]
 [-1.02020406 -0.15807423 -1.07893824]
 [ 0.98019606  1.08359645 -0.99084367]]
400


In [43]:
from sklearn.model_selection import train_test_split
x_train1,x_test1,y_train1,y_test1=train_test_split(x,y,test_size=0.3,random_state=0)


In [44]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train1,y_train1)
model.score(x_train1,y_train1)

0.6357142857142857

In [45]:
y_pred2=model.predict(x_test1)
print(y_pred2)
from sklearn.metrics import  mean_absolute_error,mean_squared_error,confusion_matrix
print("mae",mean_absolute_error(y_test1,y_pred2))
print(confusion_matrix(y_test1,y_pred2))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]
mae 0.3416666666666667
[[79  0]
 [41  0]]
