In [31]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [32]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [33]:
X

array([[-0.06368084, -0.88501856],
       [ 0.37719172,  0.43807411],
       [-1.25594042, -2.19553212],
       [ 0.65717768,  0.51804897],
       [ 0.41011294,  0.03474643],
       [-1.50925952, -1.12451966],
       [-0.07720663,  1.85524417],
       [-1.17985382, -0.33954326],
       [-1.77284361, -0.37074464],
       [ 0.09110754, -1.52695915],
       [-0.0386438 ,  0.82531548],
       [ 0.75975963,  0.69590798],
       [-0.56631699,  0.02272106],
       [ 0.83757133,  0.69002314],
       [ 0.61043611,  0.00874918],
       [ 1.00516681,  0.59898011],
       [-0.25214956, -0.89854097],
       [ 0.66233134, -0.76569558],
       [-0.03056477,  0.55248523],
       [ 0.49423149, -0.13301617],
       [-1.06963887, -0.30530015],
       [ 1.61055982, -0.76970438],
       [-1.49381248,  0.64224973],
       [ 1.8849309 , -0.50118261],
       [-0.80078315,  0.53640943],
       [ 0.23350649,  3.09010009],
       [ 0.4463704 ,  0.01037105],
       [-0.56474645,  1.36042361],
       [-0.63889606,

In [34]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [35]:
df.shape

(100, 3)

In [36]:
df.head()

feature1  feature2      target
0 -0.063681 -0.885019  -70.986378
1  0.377192  0.438074   49.046008
2 -1.255940 -2.195532 -152.354508
3  0.657178  0.518049  -12.897184
4  0.410113  0.034746   21.249064

In [37]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [39]:
from sklearn.linear_model import LinearRegression

In [40]:
lr = LinearRegression()

In [41]:
lr.fit(X_train,y_train)

LinearRegression()

In [42]:
y_pred = lr.predict(X_test)

In [61]:
X_test

array([[ 0.83154703,  0.0531142 ],
       [ 0.15679   , -1.58870632],
       [-0.07720663,  1.85524417],
       [ 0.66550743,  1.36764519],
       [ 0.45942561, -0.22199432],
       [ 0.40376535,  0.97030088],
       [ 0.36582857,  0.95179494],
       [-0.4998161 ,  0.88846104],
       [ 0.23350649,  3.09010009],
       [ 1.00516681,  0.59898011],
       [-0.59088675, -0.56410313],
       [ 0.09110754, -1.52695915],
       [ 0.47761751, -1.71100389],
       [-0.91504696,  1.03172009],
       [ 1.10251577, -0.27724612],
       [ 1.34493947, -0.84540508],
       [ 0.10519855,  0.73806612],
       [ 1.8849309 , -0.50118261],
       [ 0.72219317,  0.58256041],
       [ 0.48490268, -0.14989611]])

In [43]:
y_pred

array([ 83.81085847,  27.44660881, -12.7665292 ,  61.09141424,
        49.48060358,  37.99394371,  34.4449364 , -48.38497862,
        10.72241181,  97.6782541 , -49.65339738,  20.8190126 ,
        58.89590432, -89.01084484, 111.54202259, 137.75563498,
        10.50875388, 187.85600893,  70.57963145,  51.55672263])

In [44]:
y

array([-7.09863775e+01,  4.90460078e+01, -1.52354508e+02, -1.28971839e+01,
        2.12490644e+01, -1.70682197e+02,  1.82355984e+01, -1.44100402e+02,
       -2.29346480e+02, -1.68927580e+01, -6.92834311e+01,  7.72553203e+01,
       -6.57849841e+01,  5.46940155e+01,  7.95597702e+01,  1.66772759e+01,
       -4.22435435e+01,  4.18055096e+01,  1.08528900e+01, -2.49633276e+01,
       -1.11692155e+02,  2.11552334e+02, -1.72424686e+02,  1.29096654e+02,
       -2.81748616e+01, -2.87099782e+01,  1.65090846e+01, -1.07403494e+02,
        8.97112686e+00, -3.18641566e+00,  6.23854317e+01, -1.70185739e+02,
       -1.13554091e+02, -9.83908379e+01,  1.35186513e+02,  7.44371690e+01,
        1.24015995e+02,  1.34304098e+02,  1.25761472e+02,  1.34994035e+02,
        6.87234244e+00, -9.05642469e+01, -5.71060403e+01,  1.06213494e+01,
       -1.27517444e+02,  1.17305169e+02, -1.53787931e+01,  1.47520515e+02,
        6.99629628e+01,  4.05150418e+01,  1.28109510e+02, -1.88723253e+02,
       -1.00897004e+02, -

In [45]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 38.61137414771861
MSE 2102.333304379533
R2 score 0.6622258804758503


In [46]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T
z_final = lr.predict(final).reshape(10,10)

z = z_final



In [47]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [51]:
beta=lr.coef_

In [54]:
beta

array([96.06257545, -5.14955717])

In [53]:
beta_zero=lr.intercept_

In [56]:
X_test

array([[ 0.83154703,  0.0531142 ],
       [ 0.15679   , -1.58870632],
       [-0.07720663,  1.85524417],
       [ 0.66550743,  1.36764519],
       [ 0.45942561, -0.22199432],
       [ 0.40376535,  0.97030088],
       [ 0.36582857,  0.95179494],
       [-0.4998161 ,  0.88846104],
       [ 0.23350649,  3.09010009],
       [ 1.00516681,  0.59898011],
       [-0.59088675, -0.56410313],
       [ 0.09110754, -1.52695915],
       [ 0.47761751, -1.71100389],
       [-0.91504696,  1.03172009],
       [ 1.10251577, -0.27724612],
       [ 1.34493947, -0.84540508],
       [ 0.10519855,  0.73806612],
       [ 1.8849309 , -0.50118261],
       [ 0.72219317,  0.58256041],
       [ 0.48490268, -0.14989611]])

In [59]:
X_test[0]

array([0.83154703, 0.0531142 ])

In [62]:
pred=beta_zero+ beta[0]*X_test[0][0] + beta[1]*X_test[0][1]
pred

83.81085846962776

In [60]:
X_test[0][1]

0.053114203299456944